# Generated by Django 3.2 on 2024-06-22 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='name',
            field=models.CharField(choices=[(1, 'Grande'), (2, 'Mediana'), (3, 'Pequeña')], default=1, max_length=200),
        ),
    ]
